project_id = "edospvzmgvaytsozbcdl"

[functions.xendit-payment]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.order-tracking-verify]
verify_jwt = false

[functions.order-tracking-get]
verify_jwt = false