project_id = "edospvzmgvaytsozbcdl"

[functions.xendit-payment]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.order-tracking-verify]
verify_jwt = false

[functions.order-tracking-get]
verify_jwt = false

[functions.biteship-webhook]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.refund-webhook]
verify_jwt = false